#ifndef GOGLWRAPPER_H
#define GOGLWRAPPER_H

#include "debug.h"
#include "framebuffer.h"
#include "program.h"
#include "render_target.h"
#include "renderbuffer_color.h"
#include "renderbuffer_depth.h"
#include "renderbuffer_depth_stencil.h"
#include "renderbuffer_ms.h"
#include "renderbuffer_ms_color.h"
#include "renderbuffer_ms_depth.h"
#include "renderbuffer_ms_depth_stencil.h"
#include "renderobject.h"
#include "shader.h"
#include "shader_fragment.h"
#include "shader_geometry.h"
#include "shader_vertex.h"
#include "texture.h"
#include "texture_color.h"
#include "texture_color_srgb.h"
#include "texture_cubemap.h"
#include "texture_depth.h"
#include "texture_ms.h"
#include "texture_ms_color.h"
#include "texture_ms_depth.h"
#include "window.h"

#endif // GOGLWRAPPER_H
